name: push and pr

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: preview-url
        run: |
          echo ${{ steps.vercel-action.outputs.preview-url }}
