name: deploy website
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: vercel-action
        with:
          vercel-token: ${{ secrets.VER_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
      - name: preview-url
        run: |
          echo ${{ steps.vercel-action.outputs.preview-url }}
