name: deploy website

on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-token: 'ep2a8dRRPCmR9EgxJpIxwxUG' # Required
          vercel-args: '--prod' #Optional
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./sub-directory
